# fly.toml app configuration file generated for meowvie on 2023-05-31T09:17:41+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meowvie"
primary_region = "sin"

[env]
  ALLOW_ORIGINS="meowvie.falentio.com"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source="meowvie"
  destination="/app/database"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[http_service.concurrency]
  type = "requests"
  soft_limit = 100
  hard_limit = 150

[http_service.http_options.response.headers]
  X-Developed-By = "github.com/falentio"
